import = ["~/.config/alacritty/themes/themes/snazzy.toml"]

[font]
size = 14.0

[font.normal]
family = "CodeNewRoman Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 7

[window.dimensions]
columns = 80
lines = 24

[colors.primary]
background = '0x171421'

[colors.normal]
# black = '0x5E5C64'
# red = '0xF66151'
# green = '0x33D17A'
# yellow = '0xE9AD0C'
blue = '0x2A7BDE'
# magenta = '0xC061CB'
cyan = '0x33C7DE'
# white = '0xffffff'

[colors.bright]
# black = '0x171421'
# red = '0xc01c28'
# green = '0x26A269'
# yellow = '0xA2734C'
blue = '0x2A7BDE'
# magenta = '0xA347BA'
cyan = '0x33C7DE'
# white = '0xD0CFCC'


[keyboard]
bindings = [
  { key = "v", mods = "Control", action = "Paste" },
  { key = "n", mods = "Control", action = "SpawnNewInstance" },
  { key = "w", mods = "Control", action = "Quit" },
  { key = "c", mods = "Control", action = "Copy" },
  { key = "c", mods = "Super", chars = "\u0003" },
]
